### ISSUE TITLE
URI null host

### ISSUE THREAD

**Issue by johnhunsley** [auth0/jwks-rsa-java#21]
I'm getting an IllegalArgumentException because of a null URI host when attempting to authenitcate an OAuth JWT token with JwtAuthenticationProvider.jwtVerifier

Caused by: java.lang.IllegalArgumentException: protocol = https host = null
2018-02-14T13:48:35.702463+00:00 app[web.1]: 	at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:177) ~[na:1.8.0_161-heroku]
2018-02-14T13:48:35.702464+00:00 app[web.1]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1150) ~[na:1.8.0_161-heroku]
2018-02-14T13:48:35.702465+00:00 app[web.1]: 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[na:1.8.0_161-heroku]
2018-02-14T13:48:35.702466+00:00 app[web.1]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[na:1.8.0_161-heroku]
2018-02-14T13:48:35.702479+00:00 app[web.1]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564) ~[na:1.8.0_161-heroku]
2018-02-14T13:48:35.702480+00:00 app[web.1]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[na:1.8.0_161-heroku]
2018-02-14T13:48:35.702481+00:00 app[web.1]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[na:1.8.0_161-heroku]
2018-02-14T13:48:35.702482+00:00 app[web.1]: 	at java.net.URL.openStream(URL.java:1045) ~[na:1.8.0_161-heroku]
2018-02-14T13:48:35.702484+00:00 app[web.1]: 	at com.auth0.jwk.UrlJwkProvider.getJwks(UrlJwkProvider.java:58) ~[jwks-rsa-0.2.0.jar!/:na]
2018-02-14T13:48:35.702508+00:00 app[web.1]: 	at com.auth0.jwk.UrlJwkProvider.getAll(UrlJwkProvider.java:71) ~[jwks-rsa-0.2.0.jar!/:na]
2018-02-14T13:48:35.702509+00:00 app[web.1]: 	at com.auth0.jwk.UrlJwkProvider.get(UrlJwkProvider.java:89) ~[jwks-rsa-0.2.0.jar!/:na]
2018-02-14T13:48:35.702511+00:00 app[web.1]: 	at com.auth0.jwk.RateLimitedJwkProvider.get(RateLimitedJwkProvider.java:30) ~[jwks-rsa-0.2.0.jar!/:na]
2018-02-14T13:48:35.702512+00:00 app[web.1]: 	at com.auth0.jwk.GuavaCachedJwkProvider$1.call(GuavaCachedJwkProvider.java:49) ~[jwks-rsa-0.2.0.jar!/:na]
2018-02-14T13:48:35.702513+00:00 app[web.1]: 	at com.auth0.jwk.GuavaCachedJwkProvider$1.call(GuavaCachedJwkProvider.java:46) ~[jwks-rsa-0.2.0.jar!/:na]
2018-02-14T13:48:35.702514+00:00 app[web.1]: 	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4793) ~[guava-19.0.jar!/:na]
2018-02-14T13:48:35.702515+00:00 app[web.1]: 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542) ~[guava-19.0.jar!/:na]
2018-02-14T13:48:35.702516+00:00 app[web.1]: 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323) ~[guava-19.0.jar!/:na]
2018-02-14T13:48:35.702518+00:00 app[web.1]: 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286) ~[guava-19.0.jar!/:na]
2018-02-14T13:48:35.702519+00:00 app[web.1]: 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201) ~[guava-19.0.jar!/:na]

The exception is thrown from line 164 of sun.net.spi.DefaultProxySelector because the URI host is not being set correctly and is null. 

java -version
openjdk version "1.8.0_161-heroku"
OpenJDK Runtime Environment (build 1.8.0_161-heroku-b12)
OpenJDK 64-Bit Server VM (build 25.161-b12, mixed mode)

**Comment by lbalmaceda** [comment]
That class doesn't belong to this library. Are you sure this is the right place?

**Comment by johnhunsley** [comment]
@Ibalmaceda Yes, I think the problem is that the container this is running on is behind a proxy and it is causing issues with the HTTP connection configuration.
