### ISSUE TITLE
Accept application/jwk-set+json as content type. [SDK-2131]

### ISSUE THREAD

**Issue by eschoenawa** [auth0/jwks-rsa-java#77]
# Description

The JWKS endpoint I am using supplies the key set with the content type `application/jwk-set+json`, as is in line with the [spec](https://tools.ietf.org/html/rfc7517). I saw that since #59 the header is set to accept only the `application/json`-type though. This leads to the call to `UrlJwkProvider.getAll()` throwing a `SigningKeyNotFoundException`, because `406: Not acceptable` is returned by the server, as the content type in the accept-header is not matching the content type of the key set. I would recommend adding the possibility to supply a content type for the accept-header to the `UrlJwkProvider` or allowing it to accept either `application/json` or `application/jwk-set+json`

### Reproduction

To reproduce this simply try using the library with a JWKS-Endpoint that supplies the key set with the content type `application/jwk-set+json`.

Stacktrace (JWK URL and android package are modified):
```
com.auth0.jwk.SigningKeyNotFoundException: Cannot obtain jwks from url https://example.com/app/authorization/v1/jwks
        at com.auth0.jwk.UrlJwkProvider.getJwks(UrlJwkProvider.java:112)
        at com.auth0.jwk.UrlJwkProvider.getAll(UrlJwkProvider.java:118)
        at com.auth0.jwk.UrlJwkProvider.get(UrlJwkProvider.java:136)
        at com.myapp.fragments.setup.OAuthFragment.validateToken(OAuthFragment.kt:167)
        at com.myapp.fragments.setup.OAuthFragment.access$validateToken(OAuthFragment.kt:53)
        at com.myapp.fragments.setup.OAuthFragment$onActivityResult$1$1$1.invokeSuspend(OAuthFragment.kt:110)
        at com.myapp.fragments.setup.OAuthFragment$onActivityResult$1$1$1.invoke(Unknown Source:10)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:155)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at com.myapp.fragments.setup.OAuthFragment$onActivityResult$1$1.invokeSuspend(OAuthFragment.kt:106)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
     Caused by: java.io.FileNotFoundException: https://example.com/app/authorization/v1/jwks
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
        at com.auth0.jwk.UrlJwkProvider.getJwks(UrlJwkProvider.java:108)
        at com.auth0.jwk.UrlJwkProvider.getAll(UrlJwkProvider.java:118) 
        at com.auth0.jwk.UrlJwkProvider.get(UrlJwkProvider.java:136) 
        at com.myapp.fragments.setup.OAuthFragment.validateToken(OAuthFragment.kt:167) 
        at com.myapp.fragments.setup.OAuthFragment.access$validateToken(OAuthFragment.kt:53) 
        at com.myapp.fragments.setup.OAuthFragment$onActivityResult$1$1$1.invokeSuspend(OAuthFragment.kt:110) 
        at com.myapp.fragments.setup.OAuthFragment$onActivityResult$1$1$1.invoke(Unknown Source:10) 
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91) 
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:155) 
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1) 
        at com.myapp.fragments.setup.OAuthFragment$onActivityResult$1$1.invokeSuspend(OAuthFragment.kt:106) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) 
```

### Environment

- **Version of this library used:** 0.9.0
- I am using the library in Android.

**Comment by lbalmaceda** [comment]
I don't have access to an endpoint that exposes a JWK set like that to try it. But my testing against the Auth0 one showed that no matter the `Accept` header I sent in the request, the response was always the same (and the Content-Type header). 

What you pointed out in the spec says the JWK itself will contain a `cty` claim with the value of `application/jwk+json` but it doesn't make any mention of the response headers. Can I ask where did you take that from? 
I'm trying to understand whether this is a scoped issue or a universal one. Could it be a case that the server-side app should change its header instead? Also, can you please try to make a simple cURL request to that endpoint setting different headers and sharing here the response for each?

Thanks

**Comment by eschoenawa** [comment]
> Can I ask where did you take that from?

It seems like I misunderstood the spec on this. You are right, the content type header is not specified.

> I'm trying to understand whether this is a scoped issue or a universal one.

Considering noone has reported this yet I'd strongly go with scoped. I've never done JWT verification before so I have no experience with other endpoints to compare this to. 

> Could it be a case that the server-side app should change its header instead?

Since the content type `application/jwk-set+json` is a valid content type and the server supplies a JWK set (so exactly what the content type is intended for) the header there is correct (although it could just be set to `application/json`, which would still fit but is less specific). What may be changed however is the reaction to non-fitting Accept-Headers. According to [this](https://stackoverflow.com/a/15027174/4144974) in HTTP 1.0 you should always return status 406, but since 1.1 you can decide wether you want to return 406 or a format not specified by the accept header. It seems like most JWK-endpoints use the latter, as these headers usually don't matter there (if you contact a JWKS endpoint you probably expect a JWKS to be returned).

Sadly a tight security policy prevents me from requesting the content type to be changed or the JWKS to be delivered regardless of the accept header. So I'd still recommend adding a possibility to specify the Accept header in case you have to deviate from the default `application/json`.

> can you please try to make a simple cURL request to that endpoint setting different headers and sharing here the response for each

Here are some cURL traces for different accept headers (company URLs and names have been modified):


**With accept header set to `application/jwk-set+json`**
```
$ curl -v -H "Accept: application/jwk-set+json" https://gateway.example.com/app/authorization/v1/jwks
* STATE: INIT => CONNECT handle 0x66f160; line 1392 (connection #-5000)
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => WAITRESOLVE handle 0x66f160; line 1428 (connection #0)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 212.42.244.102...
* TCP_NODELAY set
* STATE: WAITRESOLVE => WAITCONNECT handle 0x66f160; line 1509 (connection #0)
* Connected to gateway.example.com (212.42.244.102) port 443 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x66f160; line 1561 (connection #0)
* Marked for [keep alive]: HTTP default
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* STATE: SENDPROTOCONNECT => PROTOCONNECT handle 0x66f160; line 1575 (connection #0)
{ [5 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [102 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [2901 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=DE; L=Berlin; O=COMPANY NAME; OU=it; CN=*.example.com
*  start date: Jun  6 00:00:00 2019 GMT
*  expire date: Jun 10 12:00:00 2021 GMT
*  subjectAltName: host "gateway.example.com" matched cert's "*.example.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
* STATE: PROTOCONNECT => DO handle 0x66f160; line 1596 (connection #0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* nghttp2_session_mem_recv() returns 0
} [5 bytes data]
* http2_send len=132
* h2 header: :method:GET
* h2 header: :path:/app/authorization/v1/jwks
* h2 header: :scheme:https
* h2 header: :authority:gateway.example.com
* h2 header: User-Agent:curl/7.58.0
* h2 header: Accept:application/jwk-set+json
* Using Stream ID: 1 (easy handle 0x66f160)
* before_frame_send() was called
} [5 bytes data]
* on_frame_send() was called, length = 73
> GET /app/authorization/v1/jwks HTTP/2
> Host: gateway.example.com
> User-Agent: curl/7.58.0
> Accept: application/jwk-set+json
>
* STATE: DO => DO_DONE handle 0x66f160; line 1658 (connection #0)
* multi changed, check CONNECT_PEND queue!
* STATE: DO_DONE => WAITPERFORM handle 0x66f160; line 1783 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x66f160; line 1799 (connection #0)
* http2_recv: easy 0x66f160 (stream 1)
{ [5 bytes data]
* nread=24
* Got SETTINGS
* MAX_CONCURRENT_STREAMS == 100
* ENABLE_PUSH == TRUE
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* Got SETTINGS
* MAX_CONCURRENT_STREAMS == 100
* ENABLE_PUSH == TRUE
* nghttp2_session_mem_recv() returns 24
* All data in connection buffer processed
} [5 bytes data]
* http2_recv returns AGAIN for stream 1
* multi changed, check CONNECT_PEND queue!
* http2_recv: easy 0x66f160 (stream 1)
{ [5 bytes data]
* nread=1872
* on_begin_headers() was called
* h2 status: HTTP/2 200 (easy 0x66f160)
* h2 header: cache-control: no-store
* h2 header: pragma: no-cache
* h2 header: content-type: application/jwk-set+json
* h2 header: content-length: 803
* h2 header: date: Mon, 10 Feb 2020 13:03:44 GMT
* h2 header: content-security-policy: default-src 'none'; script-src 'self' 'unsafe-inline' https://www.example.com https://sso.example.com https://static.example.com https://piwik.company.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/; style-src 'self' 'unsafe-inline' https://www.example.com https://sso.example.com https://static.example.com; img-src 'self' https://www.example.com https://sso.example.com https://static.example.com https://piwik.company.com data: ; font-src 'self' https://www.example.com https://sso.example.com https://static.example.com; connect-src 'self' https://sso.example.com https://gateway.example.com; frame-src 'self' https://sso.example.com https://www.google.com/recaptcha/; media-src 'none'; object-src 'none'; worker-src 'none'; manifest-src https://www.example.com/static/manifest.json https://sso.example.com/static/manifest.json; frame-ancestors https://sso.example.com https://www.example.com; form-action 'self' *
* on_frame_recv() header 1 stream 1
* Store 1116 bytes headers from stream 1 at 0x679080
* 803 data received for stream 1 (100481 left in buffer 0x679080, total 1919)
* on_frame_recv() header 0 stream 1
* on_stream_close(), NO_ERROR (err 0), stream 1
* Removed stream 1 hash!
* nghttp2_session_mem_recv() returns 1872
* All data in connection buffer processed
* http2_recv: returns 1919 for stream 1
* HTTP/2 found, allow multiplexing
< HTTP/2 200
< cache-control: no-store
< pragma: no-cache
< content-type: application/jwk-set+json
< content-length: 803
< date: Mon, 10 Feb 2020 13:03:44 GMT
< content-security-policy: default-src 'none'; script-src 'self' 'unsafe-inline' https://www.example.com https://sso.example.com https://static.example.com https://piwik.company.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/; style-src 'self' 'unsafe-inline' https://www.example.com https://sso.example.com https://static.example.com; img-src 'self' https://www.example.com https://sso.example.com https://static.example.com https://piwik.company.com data: ; font-src 'self' https://www.example.com https://sso.example.com https://static.example.com; connect-src 'self' https://sso.example.com https://gateway.example.com; frame-src 'self' https://sso.example.com https://www.google.com/recaptcha/; media-src 'none'; object-src 'none'; worker-src 'none'; manifest-src https://www.example.com/static/manifest.json https://sso.example.com/static/manifest.json; frame-ancestors https://sso.example.com https://www.example.com; form-action 'self' *
<
{ [803 bytes data]
* http2_recv: easy 0x66f160 (stream 1)
* h2_process_pending_input: All data in connection buffer processed
* http2_recv returns 0, http2_handle_stream_close
* nread <= 0, server closed connection, bailing
* STATE: PERFORM => DONE handle 0x66f160; line 1968 (connection #0)
* multi_done
* free header_recvbuf!!
100   803  100   803    0     0   5114      0 --:--:-- --:--:-- --:--:--  5114{"keys":[{"kty":"RSA","e":"AQAB","use":"sig","kid":"QOS1kPOmVsGjfatgEtbn-aurI4nvMWwMXbUg25AsxT0","alg":"RS256","n":"0jQaFDupLOl9dGkLfWghNk0gS1TcTHTG1Vx6_FENsiQKJITHST-TrxXR7DoSFZW2R563kyqrt8DFtQeZ1GoJclgszhaolSiZzXmzFjfAqkkxxFbCsfBiiVCoQ5vBDs5_SUB_ZiM7EJ6txmz-f1MuT3gD9kqkEA0ecB4_CbTWzabDgFXpg1xM6GmnKLsdhSXiSwBlsof2btJSZC_RK0NnSfaoiO8NHLvBjYUlIAMPLtD-byZH-9oX9VNT79UY03L0XfIDpPwweBOO7FQUSnpjDWcugmuaPXpCj6WMkbzgxXJdRsA2d_31i7JLa-lHOBBvwzbdoilaZIWEGdevuMqcpmttqIgmpprWLAubzBW47YOc_JiId92Vn3vDJtqTh3Zravj1uNFRpYvKGVh0uuhOb9ZlATzTCO1J7PRJ3CQptIxWG1EvT95tMeQE-1uBjlaGFD56hdCVlCSw_PT6hfDU6o-iiXE93M6lSOggFKqX64uDxiil7OAbGjfUa6ZsSUPpHW8gUXOdYRL0gXdGnYzYAuqV8LSPUOvlcmnpN1JMRJ36LMnZZUaM3_BQeB-IGPcy-HoHR6BwlFIaxXcQxPw7EZsOHPSEmTndZdWR0Ew1T0eN5nHNp0rIt8DuikvPiVw3qvKkTGI_TXnJMKgnmSnDTqtraeI7ihNPlpsXN197Mfk"}]}
* Connection #0 to host gateway.example.com left intact
* Expire cleared
```

**With accept header set to `application/json`**
```
$ curl -v -H "Accept: application/json" https://gateway.example.com/app/authorization/v1/jwks
* STATE: INIT => CONNECT handle 0x70f160; line 1392 (connection #-5000)
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => WAITRESOLVE handle 0x70f160; line 1428 (connection #0)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 212.42.244.102...
* TCP_NODELAY set
* STATE: WAITRESOLVE => WAITCONNECT handle 0x70f160; line 1509 (connection #0)
* Connected to gateway.example.com (212.42.244.102) port 443 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x70f160; line 1561 (connection #0)
* Marked for [keep alive]: HTTP default
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* STATE: SENDPROTOCONNECT => PROTOCONNECT handle 0x70f160; line 1575 (connection #0)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{ [5 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [102 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [2901 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=DE; L=Berlin; O=COMPANY; OU=it; CN=*.example.com
*  start date: Jun  6 00:00:00 2019 GMT
*  expire date: Jun 10 12:00:00 2021 GMT
*  subjectAltName: host "gateway.example.com" matched cert's "*.example.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
* STATE: PROTOCONNECT => DO handle 0x70f160; line 1596 (connection #0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* nghttp2_session_mem_recv() returns 0
} [5 bytes data]
* http2_send len=124
* h2 header: :method:GET
* h2 header: :path:/app/authorization/v1/jwks
* h2 header: :scheme:https
* h2 header: :authority:gateway.example.com
* h2 header: User-Agent:curl/7.58.0
* h2 header: Accept:application/json
* Using Stream ID: 1 (easy handle 0x70f160)
* before_frame_send() was called
} [5 bytes data]
* on_frame_send() was called, length = 66
> GET /app/authorization/v1/jwks HTTP/2
> Host: gateway.example.com
> User-Agent: curl/7.58.0
> Accept: application/json
>
* STATE: DO => DO_DONE handle 0x70f160; line 1658 (connection #0)
* multi changed, check CONNECT_PEND queue!
* STATE: DO_DONE => WAITPERFORM handle 0x70f160; line 1783 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x70f160; line 1799 (connection #0)
* http2_recv: easy 0x70f160 (stream 1)
{ [5 bytes data]
* nread=24
* Got SETTINGS
* MAX_CONCURRENT_STREAMS == 100
* ENABLE_PUSH == TRUE
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* Got SETTINGS
* MAX_CONCURRENT_STREAMS == 100
* ENABLE_PUSH == TRUE
* nghttp2_session_mem_recv() returns 24
* All data in connection buffer processed
} [5 bytes data]
* http2_recv returns AGAIN for stream 1
* multi changed, check CONNECT_PEND queue!
* http2_recv: easy 0x70f160 (stream 1)
{ [5 bytes data]
* nread=1009
* on_begin_headers() was called
* h2 status: HTTP/2 406 (easy 0x70f160)
* h2 header: content-length: 0
* h2 header: date: Mon, 10 Feb 2020 13:11:53 GMT
* h2 header: content-security-policy: default-src 'none'; script-src 'self' 'unsafe-inline' https://www.example.com https://sso.example.com https://static.example.com https://piwik.company.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/; style-src 'self' 'unsafe-inline' https://www.example.com https://sso.example.com https://static.example.com; img-src 'self' https://www.example.com https://sso.example.com https://static.example.com https://piwik.company.com data: ; font-src 'self' https://www.example.com https://sso.example.com https://static.example.com; connect-src 'self' https://sso.example.com https://gateway.example.com; frame-src 'self' https://sso.example.com https://www.google.com/recaptcha/; media-src 'none'; object-src 'none'; worker-src 'none'; manifest-src https://www.example.com/static/manifest.json https://sso.example.com/static/manifest.json; frame-ancestors https://sso.example.com https://www.example.com; form-action 'self' *
* on_frame_recv() header 1 stream 1
* Store 1031 bytes headers from stream 1 at 0x719080
* on_stream_close(), NO_ERROR (err 0), stream 1
* Removed stream 1 hash!
* nghttp2_session_mem_recv() returns 1009
* All data in connection buffer processed
* http2_recv: returns 1031 for stream 1
* HTTP/2 found, allow multiplexing
< HTTP/2 406
< content-length: 0
< date: Mon, 10 Feb 2020 13:11:53 GMT
< content-security-policy: default-src 'none'; script-src 'self' 'unsafe-inline' https://www.example.com https://sso.example.com https://static.example.com https://piwik.company.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/; style-src 'self' 'unsafe-inline' https://www.example.com https://sso.example.com https://static.example.com; img-src 'self' https://www.example.com https://sso.example.com https://static.example.com https://piwik.company.com data: ; font-src 'self' https://www.example.com https://sso.example.com https://static.example.com; connect-src 'self' https://sso.example.com https://gateway.example.com; frame-src 'self' https://sso.example.com https://www.google.com/recaptcha/; media-src 'none'; object-src 'none'; worker-src 'none'; manifest-src https://www.example.com/static/manifest.json https://sso.example.com/static/manifest.json; frame-ancestors https://sso.example.com https://www.example.com; form-action 'self' *
<
* http2_recv: easy 0x70f160 (stream 1)
* h2_process_pending_input: All data in connection buffer processed
* http2_recv returns 0, http2_handle_stream_close
{ [0 bytes data]
* http2_recv: easy 0x70f160 (stream 1)
* STATE: PERFORM => DONE handle 0x70f160; line 1968 (connection #0)
* multi_done
* free header_recvbuf!!
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host gateway.example.com left intact
* Expire cleared
```

**With no accept header set**
```
$ curl -v https://gateway.example.com/app/authorization/v1/jwks
* STATE: INIT => CONNECT handle 0x25cf160; line 1392 (connection #-5000)
* Added connection 0. The cache now contains 1 members
* STATE: CONNECT => WAITRESOLVE handle 0x25cf160; line 1428 (connection #0)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 212.42.244.102...
* TCP_NODELAY set
* STATE: WAITRESOLVE => WAITCONNECT handle 0x25cf160; line 1509 (connection #0)
* Connected to gateway.example.com (212.42.244.102) port 443 (#0)
* STATE: WAITCONNECT => SENDPROTOCONNECT handle 0x25cf160; line 1561 (connection #0)
* Marked for [keep alive]: HTTP default
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
} [5 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* STATE: SENDPROTOCONNECT => PROTOCONNECT handle 0x25cf160; line 1575 (connection #0)
{ [5 bytes data]
* TLSv1.2 (IN), TLS handshake, Server hello (2):
{ [102 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [2901 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [333 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [70 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
{ [1 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=DE; L=Berlin; O=COMPANY; OU=it; CN=*.example.com
*  start date: Jun  6 00:00:00 2019 GMT
*  expire date: Jun 10 12:00:00 2021 GMT
*  subjectAltName: host "gateway.example.com" matched cert's "*.example.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
* STATE: PROTOCONNECT => DO handle 0x25cf160; line 1596 (connection #0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* nghttp2_session_mem_recv() returns 0
} [5 bytes data]
* http2_send len=111
* h2 header: :method:GET
* h2 header: :path:/app/authorization/v1/jwks
* h2 header: :scheme:https
* h2 header: :authority:gateway.example.com
* h2 header: User-Agent:curl/7.58.0
* h2 header: Accept:*/*
* Using Stream ID: 1 (easy handle 0x25cf160)
* before_frame_send() was called
} [5 bytes data]
* on_frame_send() was called, length = 58
> GET /app/authorization/v1/jwks HTTP/2
> Host: gateway.example.com
> User-Agent: curl/7.58.0
> Accept: */*
>
* STATE: DO => DO_DONE handle 0x25cf160; line 1658 (connection #0)
* multi changed, check CONNECT_PEND queue!
* STATE: DO_DONE => WAITPERFORM handle 0x25cf160; line 1783 (connection #0)
* STATE: WAITPERFORM => PERFORM handle 0x25cf160; line 1799 (connection #0)
* http2_recv: easy 0x25cf160 (stream 1)
{ [5 bytes data]
* nread=24
* Got SETTINGS
* MAX_CONCURRENT_STREAMS == 100
* ENABLE_PUSH == TRUE
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* Got SETTINGS
* MAX_CONCURRENT_STREAMS == 100
* ENABLE_PUSH == TRUE
* nghttp2_session_mem_recv() returns 24
* All data in connection buffer processed
} [5 bytes data]
* http2_recv returns AGAIN for stream 1
* multi changed, check CONNECT_PEND queue!
* http2_recv: easy 0x25cf160 (stream 1)
{ [5 bytes data]
* nread=1872
* on_begin_headers() was called
* h2 status: HTTP/2 200 (easy 0x25cf160)
* h2 header: cache-control: no-store
* h2 header: pragma: no-cache
* h2 header: content-type: application/jwk-set+json
* h2 header: content-length: 803
* h2 header: date: Mon, 10 Feb 2020 13:17:33 GMT
* h2 header: content-security-policy: default-src 'none'; script-src 'self' 'unsafe-inline' https://www.example.com https://sso.example.com https://static.example.com https://piwik.company.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/; style-src 'self' 'unsafe-inline' https://www.example.com https://sso.example.com https://static.example.com; img-src 'self' https://www.example.com https://sso.example.com https://static.example.com https://piwik.company.com data: ; font-src 'self' https://www.example.com https://sso.example.com https://static.example.com; connect-src 'self' https://sso.example.com https://gateway.example.com; frame-src 'self' https://sso.example.com https://www.google.com/recaptcha/; media-src 'none'; object-src 'none'; worker-src 'none'; manifest-src https://www.example.com/static/manifest.json https://sso.example.com/static/manifest.json; frame-ancestors https://sso.example.com https://www.example.com; form-action 'self' *
* on_frame_recv() header 1 stream 1
* Store 1116 bytes headers from stream 1 at 0x25d9c90
* 803 data received for stream 1 (100481 left in buffer 0x25d9c90, total 1919)
* on_frame_recv() header 0 stream 1
* on_stream_close(), NO_ERROR (err 0), stream 1
* Removed stream 1 hash!
* nghttp2_session_mem_recv() returns 1872
* All data in connection buffer processed
* http2_recv: returns 1919 for stream 1
* HTTP/2 found, allow multiplexing
< HTTP/2 200
< cache-control: no-store
< pragma: no-cache
< content-type: application/jwk-set+json
< content-length: 803
< date: Mon, 10 Feb 2020 13:17:33 GMT
< content-security-policy: default-src 'none'; script-src 'self' 'unsafe-inline' https://www.example.com https://sso.example.com https://static.example.com https://piwik.company.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/; style-src 'self' 'unsafe-inline' https://www.example.com https://sso.example.com https://static.example.com; img-src 'self' https://www.example.com https://sso.example.com https://static.example.com https://piwik.company.com data: ; font-src 'self' https://www.example.com https://sso.example.com https://static.example.com; connect-src 'self' https://sso.example.com https://gateway.example.com; frame-src 'self' https://sso.example.com https://www.google.com/recaptcha/; media-src 'none'; object-src 'none'; worker-src 'none'; manifest-src https://www.example.com/static/manifest.json https://sso.example.com/static/manifest.json; frame-ancestors https://sso.example.com https://www.example.com; form-action 'self' *
<
{ [803 bytes data]
* http2_recv: easy 0x25cf160 (stream 1)
* h2_process_pending_input: All data in connection buffer processed
* http2_recv returns 0, http2_handle_stream_close
* nread <= 0, server closed connection, bailing
* STATE: PERFORM => DONE handle 0x25cf160; line 1968 (connection #0)
* multi_done
* free header_recvbuf!!
100   803  100   803    0     0   2236      0 --:--:-- --:--:-- --:--:--  2236{"keys":[{"kty":"RSA","e":"AQAB","use":"sig","kid":"QOS1kPOmVsGjfatgEtbn-aurI4nvMWwMXbUg25AsxT0","alg":"RS256","n":"0jQaFDupLOl9dGkLfWghNk0gS1TcTHTG1Vx6_FENsiQKJITHST-TrxXR7DoSFZW2R563kyqrt8DFtQeZ1GoJclgszhaolSiZzXmzFjfAqkkxxFbCsfBiiVCoQ5vBDs5_SUB_ZiM7EJ6txmz-f1MuT3gD9kqkEA0ecB4_CbTWzabDgFXpg1xM6GmnKLsdhSXiSwBlsof2btJSZC_RK0NnSfaoiO8NHLvBjYUlIAMPLtD-byZH-9oX9VNT79UY03L0XfIDpPwweBOO7FQUSnpjDWcugmuaPXpCj6WMkbzgxXJdRsA2d_31i7JLa-lHOBBvwzbdoilaZIWEGdevuMqcpmttqIgmpprWLAubzBW47YOc_JiId92Vn3vDJtqTh3Zravj1uNFRpYvKGVh0uuhOb9ZlATzTCO1J7PRJ3CQptIxWG1EvT95tMeQE-1uBjlaGFD56hdCVlCSw_PT6hfDU6o-iiXE93M6lSOggFKqX64uDxiil7OAbGjfUa6ZsSUPpHW8gUXOdYRL0gXdGnYzYAuqV8LSPUOvlcmnpN1JMRJ36LMnZZUaM3_BQeB-IGPcy-HoHR6BwlFIaxXcQxPw7EZsOHPSEmTndZdWR0Ew1T0eN5nHNp0rIt8DuikvPiVw3qvKkTGI_TXnJMKgnmSnDTqtraeI7ihNPlpsXN197Mfk"}]}
* Connection #0 to host gateway.example.com left intact
```

**Comment by jimmyjames** [comment]
It makes sense to allow the `jwk-set+json` accept header to be sent. The default should remain `application/json`, but we could allow a configuration point to set the header to a different value. Might make sense to be more generic, and allow for the setting of any headers required.

We've added this to our backlog, though would be willing to review a PR if available before we pick up the work. Thanks!
